### ISSUE TITLE
TLS WebSockets capability flag in geocode.json

### ISSUE THREAD

**Issue by yoursunny** [WU-ARL/ndnmap#1]
<http://ndnmap.arl.wustl.edu/json/geocode/> is used by NDN-FCH to find testbed routers closest to a client's geolocation.
Recently, a subset of routers are configured to accept WebSockets connection over TLS, and NDN-FCH should be updated in named-data/ndn-fch#1 to return a router in this subset.
In order to support that, `/json/geocode.json` feed should be extended to indicate whether a router supports TLS WebSockets or not. An entry should include `"ws-tls": true` if TLS WebSockets are supported on this router.

**Comment by jdehart1** [comment]
I have added ws-tls to the ndnmap geocode.json file and marked UCLA, WU and ARIZONA as true.
All other nodes are false.

I have also set up TLS support on all the other nodes that have a FQDN. I will next ask the operators
to get port 443 open to Testbed nodes.  

Then all the other nodes that do not have a FQDN, I’ll work on the operators to see if we can get
that set up at their sites.
